# eosio.token
cleos create account eosio eosio.token EOS6QahzfDoDvdXGTjV8YWxZ6vEYHqxen9v16U1aRZj7kWiPpmb4E EOS6QahzfDoDvdXGTjV8YWxZ6vEYHqxen9v16U1aRZj7kWiPpmb4E
cleos create account eosio eosio.msig EOS6QahzfDoDvdXGTjV8YWxZ6vEYHqxen9v16U1aRZj7kWiPpmb4E EOS6QahzfDoDvdXGTjV8YWxZ6vEYHqxen9v16U1aRZj7kWiPpmb4E
cleos create account eosio eosio.nft EOS6QahzfDoDvdXGTjV8YWxZ6vEYHqxen9v16U1aRZj7kWiPpmb4E EOS6QahzfDoDvdXGTjV8YWxZ6vEYHqxen9v16U1aRZj7kWiPpmb4E
cleos wallet import 5KTdTrTr1pYzLQjo8hSUmtzShEtHaonmVfHF7mAdv3azpxhE6Xr

cleos set contract eosio.token $EOS_BUILD_DIR/contracts/eosio.token -p eosio.token
cleos set contract eosio.msig $EOS_BUILD_DIR/contracts/eosio.token -p eosio.msig
cleos set contract eosio.nft $EOS_BUILD_DIR/contracts/eosio.nft -p eosio.nft
